import type { Pool } from 'pg';
import { generateCustomers, TARIFF_MINOR_PER_KILOLITRE } from '@/seed/generate';
import type { SyntheticCustomer } from '@/seed/generate';
import { err, ok, type Result } from '@/domain/result';
import type { ErpCustomerPort, ErpError } from '@/ports/erp';
import type {
  Customer,
  CustomerId,
  Invoice,
  InvoiceId,
  NewCustomer,
  PaymentReceipt,
  UsagePoint,
} from '@/domain/types';
import type { Money } from '@/domain/money';

/**
 * Customers, invoices and usage without Odoo.
 *
 * The seeded customers are generated by the same function the seed script
 * uses, so a demonstration shows the same two hundred people, the same usage
 * and the same bills on every restart, and needs nothing loaded into it.
 *
 * Two things are not generated, because a demonstration in which they vanished
 * would read as a defect rather than as an absent back end:
 *
 *   - a customer who opens an account is stored, in `demo_customer`
 *   - an invoice that has been paid reads as paid, from the `payment` table
 *     the portal already writes
 *
 * `payment` is the demonstration's system of record for money. That is not a
 * shortcut: `src/payments/pay.ts` writes the row *before* it tells the ERP, and
 * the table already carries a constraint permitting at most one successful
 * payment per invoice. Deriving "paid" from it is reading the record that
 * already exists rather than keeping a second one.
 */

const CUSTOMER_COUNT = 200;
/** Three most recent months become invoices, as the seed does. */
const INVOICE_MONTHS = 3;

interface StoredCustomer {
  readonly id: string;
  readonly name: string;
  readonly email: string;
  readonly phone: string | null;
  readonly city: string | null;
}

export class DemoCustomerAdapter implements ErpCustomerPort {
  private readonly seeded: readonly SyntheticCustomer[] = generateCustomers(CUSTOMER_COUNT);
  private readonly byEmail = new Map<string, number>();

  constructor(private readonly pool: Pool) {
    this.seeded.forEach((c, i) => this.byEmail.set(c.email.toLowerCase(), i));
  }

  /**
   * Identifiers are `demo-<n>` for a generated customer and `stored-<n>` for one
   * created here, so an identifier says which store answers for it. A bare
   * number would collide the moment onboarding created its first customer.
   */
  private seededIndex(id: CustomerId): number | null {
    const m = /^demo-(\d+)$/.exec(id);
    if (!m) return null;
    const i = Number(m[1]);
    return i >= 0 && i < this.seeded.length ? i : null;
  }

  private toCustomer(index: number, balanceMinor: Money): Customer {
    const c = this.seeded[index]!;
    return {
      id: `demo-${index}`,
      name: c.name,
      email: c.email,
      phone: c.phone,
      city: c.city,
      balanceMinor,
    };
  }

  async createCustomer(input: NewCustomer): Promise<Result<CustomerId, ErpError>> {
    if (this.byEmail.has(input.email.toLowerCase())) {
      return err({ kind: 'rejected', message: `a customer already exists for ${input.email}` });
    }
    try {
      const { rows } = await this.pool.query<{ id: string }>(
        `INSERT INTO demo_customer (email, name, phone, city, street)
         VALUES ($1, $2, $3, $4, $5)
         ON CONFLICT (email) DO NOTHING
         RETURNING id`,
        [input.email, input.name, input.phone ?? null, input.city ?? null, input.street ?? null],
      );
      if (rows.length === 0) {
        return err({ kind: 'rejected', message: `a customer already exists for ${input.email}` });
      }
      return ok(`stored-${rows[0]!.id}`);
    } catch (cause) {
      return err({ kind: 'unavailable', message: 'the customer store did not answer', cause });
    }
  }

  async getCustomer(id: CustomerId): Promise<Result<Customer, ErpError>> {
    const index = this.seededIndex(id);
    if (index !== null) {
      const invoices = await this.listInvoices(id);
      const owed = invoices.ok
        ? invoices.value.reduce((sum, i) => sum + i.dueMinor, 0)
        : 0;
      return ok(this.toCustomer(index, owed as Money));
    }

    const stored = await this.readStored(id);
    if (!stored.ok) return stored;
    // A customer who has just opened an account has no history and owes
    // nothing. Inventing a bill for them would be inventing a debt.
    return ok({ ...stored.value, balanceMinor: 0 as Money });
  }

  private async readStored(id: CustomerId): Promise<Result<StoredCustomer, ErpError>> {
    const m = /^stored-(\d+)$/.exec(id);
    if (!m) return err({ kind: 'not_found', message: `no customer ${id}` });
    try {
      const { rows } = await this.pool.query<{
        id: string;
        name: string;
        email: string;
        phone: string | null;
        city: string | null;
      }>('SELECT id, name, email, phone, city FROM demo_customer WHERE id = $1', [m[1]]);
      const row = rows[0];
      if (!row) return err({ kind: 'not_found', message: `no customer ${id}` });
      // The spread comes first, deliberately. With `id` written before it, the
      // raw numeric id from the row would overwrite the prefixed one and every
      // later lookup would fail to recognise its own identifier. The compiler
      // caught it; the tests would have caught it second.
      return ok({ ...row, id: `stored-${row.id}` });
    } catch (cause) {
      return err({ kind: 'unavailable', message: 'the customer store did not answer', cause });
    }
  }

  async findCustomerByEmail(email: string): Promise<Result<Customer | null, ErpError>> {
    const index = this.byEmail.get(email.toLowerCase());
    if (index !== undefined) return this.getCustomer(`demo-${index}`);

    try {
      const { rows } = await this.pool.query<{ id: string }>(
        'SELECT id FROM demo_customer WHERE lower(email) = lower($1)',
        [email],
      );
      const row = rows[0];
      // Absent is a null answer, not an error - the same contract the Odoo
      // adapter honours, and the reason a caller can tell "no such customer"
      // from "the system of record is down".
      if (!row) return ok(null);
      return this.getCustomer(`stored-${row.id}`);
    } catch (cause) {
      return err({ kind: 'unavailable', message: 'the customer store did not answer', cause });
    }
  }

  async listInvoices(id: CustomerId): Promise<Result<readonly Invoice[], ErpError>> {
    const index = this.seededIndex(id);
    if (index === null) {
      // Stored customers are new and have no billing history.
      const stored = await this.readStored(id);
      return stored.ok ? ok([]) : stored;
    }

    const usage = this.seeded[index]!.usage.slice(-INVOICE_MONTHS);
    const ids = usage.map((_, n) => `demo-inv-${index}-${n}`);

    let paid: Set<string>;
    try {
      const { rows } = await this.pool.query<{ invoice_id: string }>(
        `SELECT invoice_id FROM payment
          WHERE status = 'succeeded' AND invoice_id = ANY($1::text[])`,
        [ids],
      );
      paid = new Set(rows.map((r) => r.invoice_id));
    } catch (cause) {
      return err({ kind: 'unavailable', message: 'the payment record did not answer', cause });
    }

    return ok(
      usage.map((point, n) => {
        const invoiceId = ids[n]!;
        const settled = paid.has(invoiceId);
        return {
          id: invoiceId,
          // A reference exists once an invoice is issued. These all are; a
          // draft is the state the real adapter reports as a null reference,
          // and the demonstration never produces one.
          reference: `INV/${point.month}/${String(index + 1).padStart(4, '0')}-${n + 1}`,
          status: settled ? 'paid' : 'open',
          totalMinor: point.costMinor,
          dueMinor: settled ? (0 as Money) : point.costMinor,
          dueDate: `${point.month}-28`,
        } satisfies Invoice;
      }),
    );
  }

  async getUsage(id: CustomerId, months: number): Promise<Result<readonly UsagePoint[], ErpError>> {
    const index = this.seededIndex(id);
    if (index === null) {
      const stored = await this.readStored(id);
      return stored.ok ? ok([]) : stored;
    }
    const all = this.seeded[index]!.usage;
    return ok(all.slice(Math.max(0, all.length - months)));
  }

  async recordPayment(
    invoice: InvoiceId,
    receipt: PaymentReceipt,
  ): Promise<Result<void, ErpError>> {
    // Nothing to do, and that is the design rather than an omission.
    //
    // `src/payments/pay.ts` writes the row to `payment` before it calls this,
    // and `listInvoices` above reads that table to decide whether an invoice is
    // paid. The fact is already recorded. Writing it again here would give the
    // demonstration two records of one payment and a way for them to disagree.
    void invoice;
    void receipt;
    return ok(undefined);
  }
}
