import { generatePlans } from '@/seed/generate';
import { ok } from '@/domain/result';
import type { Result } from '@/domain/result';
import type { SearchPort, SearchError } from '@/ports/search';
import type { Page, Plan, PlanQuery } from '@/domain/types';

/**
 * The plan catalogue, searched in process.
 *
 * `MeilisearchAdapter` asks a search engine. There is no search engine in a
 * demonstration, and standing one up to filter a few dozen rows would be a
 * container that exists to make a demonstration look like production.
 *
 * The catalogue is generated by the same function the seed uses, so the
 * demonstration shows exactly the plans a seeded local stack shows, and shows
 * them identically on every restart.
 *
 * Matching is deliberately simpler than Meilisearch's. It is substring,
 * case-insensitive, across name and description - no typo tolerance, no
 * ranking. A demonstration that silently behaved better than the real adapter
 * would mislead about the real adapter; behaving a little worse, visibly, does
 * not.
 */
export class DemoSearchAdapter implements SearchPort {
  private readonly plans: readonly Plan[] = generatePlans();

  async searchPlans(query: PlanQuery): Promise<Result<Page<Plan>, SearchError>> {
    const text = query.text?.trim().toLowerCase();

    const matched = this.plans.filter((plan) => {
      if (query.category && plan.category !== query.category) return false;
      if (
        query.maxMonthlyPriceMinor !== undefined &&
        plan.monthlyPriceMinor > query.maxMonthlyPriceMinor
      ) {
        return false;
      }
      if (!text) return true;
      return `${plan.name} ${plan.description}`.toLowerCase().includes(text);
    });

    const offset = query.offset ?? 0;
    const limit = query.limit ?? matched.length;

    // `total` is the number that matched, not the number returned. A caller
    // paging through results needs to know how many there are.
    return ok({ items: matched.slice(offset, offset + limit), total: matched.length });
  }

  async indexPlans(): Promise<Result<void, SearchError>> {
    // Nothing to index: the catalogue is generated, not stored. Succeeding is
    // correct rather than lenient - the postcondition a caller wants is "the
    // plans are searchable", and they already are.
    return ok(undefined);
  }
}
